title: Complete list of all GitHub Profile badges and Achievements
description: Complete list of all GitHub Profile badges and Achievements
permalink: pretty

lang: en
logo_url: https://avatars.githubusercontent.com/u/117988194?s=200&v=4

navbar_link_text: GitHub profile achievements
navbar_button_text: This page on GitHub

# For remote theme support
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/jekyll-theme
